### ISSUE TITLE
Support for all release targets of .NET MAUI?

### ISSUE THREAD

**Issue by Nerketur** [CollinAlpert/Lombok.NET#11]
I'm currently exploring .NET MAUI, and as it is, this project works brilliantly, but only for the android portion of .NET MAUI.  If I have time, I'll look through the code and see if I can send a pull request once I figure out how to fix it, but until then, I just felt it was best if you were aware.  :)

In other words, this doesn't currently play well with other targets for a multi-target project, such as .NET MAUI.  At least, not when creating such an app from the provided template for .NET MAUI.

**Comment by CollinAlpert** [comment]
Thanks for the heads-up! I am working on an M1 Mac without Rosetta 2 (because reasons), so I can't really test a MAUI project. I'd still be grateful if you could send a reproduction project (either .zip or GitHub-Repository) and let me know exactly what does not work. Maybe I can further pinpoint the issue.

**Comment by CollinAlpert** [comment]
Closing due to lack of further feedback. Feel free to reopen the issue with additional feedback anytime.
