### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Christophe06410** [CollinAlpert/Lombok.NET#2]
Hi,
I am working with both Java and C#.
What I use in Lombok for Java is the following:
 - Generation of default and all-property Constructors (these you have in Lombok.Net)
 - Generation of ToString method with all properties (seems to be missing)
 - Generation of Properties from fields (did not see this either, but might not be so important in regular classes, but when thinking of WPF or Xamarin, raising an IPropertyChanged would be great)
 - Generation of Equals and GetHash methods.

Hope you find these ideas helpful.

In the meantime, I am down to writing the code myself :)
Thank you for your help.
Christophe

**Comment by CollinAlpert** [comment]
Thanks so much for these ideas, I'll get started and close the issue when I'm done.

**Comment by CollinAlpert** [comment]
Thanks again for your input. I have managed to implement these features, so check out the README for more information. 

I have put the Equals/HashCode generators on the roadmap and will implement those later on, since there are a lot of different opinions out there when an object is equal to another and especially what is a good hash code. I will need to do some more research on this topic first.
