### ISSUE TITLE
@With need to return a copy of the object?

### ISSUE THREAD

**Issue by cristi-ruja** [CollinAlpert/Lombok.NET#44]
The `@With` in Lombok (Java) is returning a copy of the object if the provided property was changed

```java
protected WithExample withName( String name) {
    return this.name == name ? this : new WithExample(name, age,....);
}
```

current .NET implementation is more like a Builder?
So ideally will like to have a new instance of the object with the new property set (and rest of the properties) This will help with immutable objects.

Maybe add  `[WithNew]`  if you consider original C# implementation as expected.
Also would be nice to have it working on Properties?

**Comment by CollinAlpert** [comment]
This library is not an exact copy of Java's Lombok and it does not work the same. Returning the same instance is a lot more performant, which is why the current implementation does so. The problem is also that a constructor would be required for this immutable approach to work, making validation a lot more complicated. I would happily accept a PR for this if you would like to submit one, however I don't deem this feature important enough to implement it myself.

**Comment by CollinAlpert** [comment]
> Also would be nice to have it working on Properties?

Properties work by setting the `MemberType` value in the `[With]` attribute like this:
```csharp
[With(MemberType = MemberType.Property, AccessTypes = AccessTypes.Public)]
public partial class Person
{
  public string Name { get; set; }
}
```
